/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.model.Model_Admin;
import com.raven.swing.table.EventAction;
import javax.swing.ImageIcon;

/**
 *
 * @author franc
 */
public class Form_3 extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_3() {
        initComponents();
        table1.fixTable(jScrollPane1);
        initTableData();
    }

    private void initTableData() {
        EventAction eventAction = new EventAction() {
            @Override
            public void delete(Model_Admin admin) {
                System.out.println("Supprimer");

            }

            @Override
            public void update(Model_Admin admin) {
                System.out.println("Modification");
            }
        };
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "test", "test", "test@gmail.com", "0612121212").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Francis", "ZHAO", "francis.zhao2000@gmail.com", "0612779621").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile1.jpg")), "Geran", "Cocagne", "gerancocagnepro@gmail.com", "0612345678").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile2.jpg")), "Amir", "KHALDI", "amirkhaldi17@gmail.com", "0656854563").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile3.jpg")), "Raphael", "NGUYENDANG", "raphaelnguyendang@gmail.com", "0658565859").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Francis", "ZHAO", "francis.zhao2000@gmail.com", "0612779621").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Francis", "ZHAO", "francis.zhao2000@gmail.com", "0612779621").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Francis", "ZHAO", "francis.zhao2000@gmail.com", "0612779621").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Francis", "ZHAO", "francis.zhao2000@gmail.com", "0612779621").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Francis", "ZHAO", "francis.zhao2000@gmail.com", "0612779621").toRowTable(eventAction));
        table1.addRow(new Model_Admin(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Francis", "ZHAO", "francis.zhao2000@gmail.com", "0612779621").toRowTable(eventAction));
        
        
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.raven.swing.table.Table();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));

        jPanel1.setBackground(new java.awt.Color(117, 202, 240));

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 0, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des admins");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prénom", "Nom", "Email", "Téléphone", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        jButton1.setBackground(new java.awt.Color(37, 157, 209));
        jButton1.setText("Ajouter un admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.swing.table.Table table1;
    // End of variables declaration//GEN-END:variables
}
