/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.main.Main;
import com.raven.dialog.Message;
import com.raven.model.Model_Oeuvre;
import com.raven.swing.table.EventActionOeuvre;
import javax.swing.ImageIcon;

/**
 *
 * @author franc
 */
public class Form_2 extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_2() {
        initComponents();
        tableOeuvre1.fixTable(jScrollPane1);
        initTableData();
    }
    
    private void initTableData() {
        EventActionOeuvre eventActionOeuvre = new EventActionOeuvre() {
            @Override
            public void deleteOeuvre(Model_Oeuvre oeuvre) {
                showMessage("Supprimer un oeuvre : "+oeuvre.getTitre());
            }

            @Override
            public void updateOeuvre(Model_Oeuvre oeuvre) {
                showMessage("Modifier un oeuvre : "+oeuvre.getTitre());
            }
        };
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/Figurine1.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/Figurine2.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/Bijoux1.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/Sculpture.jpg")), "Femme à 3 têtes", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
        tableOeuvre1.addRow(new Model_Oeuvre(new ImageIcon(getClass().getResource("/com/raven/icon/profile.jpg")), "Figurine", "Pablo Picasso", "Figurine stylée", "Prêt").toRowTable(eventActionOeuvre));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void showMessage(String message) {
        Message obj= new Message(Main.getFrames()[0], true);
        obj.showMessage(message);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOeuvre1 = new com.raven.swing.table.TableOeuvre();
        jLabel2 = new javax.swing.JLabel();
        button1 = new com.raven.swing.Button();
        searchBar1 = new com.raven.component.SearchBar();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(242, 242, 242));

        jPanel1.setBackground(new java.awt.Color(117, 202, 240));

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 0, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des oeuvres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tableOeuvre1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre", "Artiste", "Description", "Etat", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOeuvre1);
        if (tableOeuvre1.getColumnModel().getColumnCount() > 0) {
            tableOeuvre1.getColumnModel().getColumn(0).setMinWidth(200);
            tableOeuvre1.getColumnModel().getColumn(0).setMaxWidth(200);
            tableOeuvre1.getColumnModel().getColumn(1).setMinWidth(120);
            tableOeuvre1.getColumnModel().getColumn(1).setMaxWidth(120);
            tableOeuvre1.getColumnModel().getColumn(3).setMinWidth(50);
            tableOeuvre1.getColumnModel().getColumn(3).setMaxWidth(50);
            tableOeuvre1.getColumnModel().getColumn(4).setMinWidth(180);
            tableOeuvre1.getColumnModel().getColumn(4).setMaxWidth(180);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Oeuvres");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button1.setBackground(new java.awt.Color(37, 157, 209));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Ajouter un oeuvre");
        button1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titre", "titre 1", "titre 2", " " }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artiste", "Pablo Picasso", "Francis Zhao", " " }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "État", "Prêt", "Restauration", "Emprunt", "Acquise", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button button1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.raven.component.SearchBar searchBar1;
    private com.raven.swing.table.TableOeuvre tableOeuvre1;
    // End of variables declaration//GEN-END:variables
}
